---
- name: Install Jenkins and dependencies
  hosts: all
  become: true
  vars:
    jenkins_admin_user: "admin"

  tasks:
    - name: Update APT package list
      apt:
        update_cache: yes

    - name: Install fontconfig and OpenJDK 17
      apt:
        name:
          - fontconfig
          - openjdk-17-jre
        state: present

    - name: Add Jenkins repository key
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc

    - name: Add Jenkins repository
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/jenkins.list
        line: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
        create: yes

    - name: Update APT package list after adding Jenkins repo
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start and enable Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: yes

    - name: Ensure Jenkins service is up and running
      wait_for:
        port: 8080
        timeout: 120

    - name: Copy plugins.txt file to host machine
      ansible.builtin.copy:
          src: plugins.txt
          dest: /home/ubuntu/plugins.txt

    - name: Install plugins using Jenkins CLI
      command: |
        java -jar /usr/share/jenkins/jenkins.war -s http://localhost:8080/jenkins install-plugin $(cat /home/ubuntu/plugins.txt)
      args:
        creates: /var/lib/jenkins/plugins
      notify:
        - Restart Jenkins

    - name: Print Jenkins initial admin password
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_password

    - name: Display Jenkins initial admin password
      debug:
        msg: "Jenkins initial admin password is {{ jenkins_password.stdout }}"

  handlers:
    - name: Restart Jenkins
      systemd:
        name: jenkins
        state: restarted






    - name: Read the initial admin password
      ansible.builtin.shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_admin_password
      failed_when: false

    - name: Ensure Jenkins CLI is available
      get_url:
        url: "http://{{ ansible_host }}:8080/jnlpJars/jenkins-cli.jar"
        dest: "/tmp/jenkins-cli.jar"
      when: ansible_facts['os_family'] != 'Ubuntu'

    - name: Fetch Jenkins crumb for CLI authentication
      uri:
        url: "http://{{ ansible_host }}:8080/crumbIssuer/api/json"
        user: "{{ jenkins_admin_user }}"
        password: "{{ jenkins_admin_password }}"
        method: GET
        return_content: yes
      register: crumb_response

    - name: Extract Jenkins crumb
      set_fact:
        jenkins_crumb: "{{ crumb_response.json.crumb }}"

    - name: Update all Jenkins plugins
      command: >
        java -jar /tmp/jenkins-cli.jar
        -s http://{{ ansible_host }}:8080/
        -auth {{ jenkins_admin_user }}:{{ jenkins_admin_password }}
        -webSocket
        install-plugin {{ item }}
      with_items:
        - blueocean
      args:
        creates: "/var/lib/jenkins/plugins/{{ item }}.hpi"

    - name: Restart Jenkins to apply updates
      service:
        name: jenkins
        state: restarted
